version: '3.8'

networks:
    app-network:
        driver: bridge

services: 

    mailhog:
        image: mailhog/mailhog:latest
        container_name: mailhog
        ports:
          - "8001:8025"

    apachephp: 
        build: .docker/apache
        #image: php:8.1.3RC1-apache
        container_name: apachephp
        restart: always
        tty: true
        ports:
            - "8002:80"
        volumes:
            - ./application/html:/var/www/html
        environment: 
            - MYSQL_DATABASE=dev
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
        networks:
            - app-network 
        depends_on: 
            - db
            - redis

    redis:
        image: redis:alpine
        expose:
            - 6379
        networks:
            - app-network 

    db:
        image: mariadb
        #command: --inno-db-use-native-aio=0
        container_name: db
        restart: always
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "dev"
        volumes:
            - ./application/database:/var/lib/mysql
        networks:
            - app-network


    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
          - 8003:80
        environment:
          - PMA_ARBITRARY=1
        depends_on: 
          - db
          - apachephp
        networks:
          - app-network